http {
    # AMBIENTE PROD
    server{
        listen 80;
        server_name localhost;
        location / {
            proxy_pass http://fe-prod:80;
        }
        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://sio-backend-green:3000;
        }
    }

    # AMBIENTE TEST
    server{
        listen 8080;
        location / {
            proxy_pass http://fe-test:80;
        }
        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://sio-backend-blue:3000;
        }
    }

    # AMBIENTE SVI
    server{
        listen 8999;
        location / {
            proxy_pass http://fe-sio:80;
        }
        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://sio-backend-blue:3000;
        }
    }
}

stream {
    server {
        listen 5432;
        # Qui posso aggiungere i vari IP a cui dare l'accesso, per ora accetto le connessioni solo da me stesso
        allow 127.0.0.1;
        # Rifiuto tutte le connessioni provenienti da altri IP
        deny all;
        proxy_pass db:5432;
    }
}